spring:
  application:
    name: Temperature Blanket
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  address: 0.0.0.0
  port: 8080


api:
  security:
    token:
      secret: ${JWT_SECRET}
    login:
      username: ${JWT_USERNAME}
      password: ${JWT_PASSWORD}
